### ISSUE TITLE
Dependency aporat/slim-json-helpers doesn't seem to exist

### ISSUE THREAD

**Issue by paulinevos** [joindin/callingallpapers-api#38]
While running `composer install` I got a `404` for dependency `aporat/slim-json-helpers`. The repo either doesn't seem to exist anymore or is private now.

The only usage is in `Callingallpapers\Api\Middleware\Renderer`.

**Comment by heiglandreas** [comment]
Thanks for raising that issue! I'll check that ASAP and keep you posted! 

Not sure ATM (and out of my head) why it's used in the first place…
