### ISSUE TITLE
Dates and locations from papercall being improperly parsed

### ISSUE THREAD

**Issue by karllhughes** [joindin/callingallpapers-api#52]
I noticed a few days ago that many of the dates from papercall CFPs are showing up as 12/31/1969 on the site. It also seems from looking at the data that locations are not being parsed correctly.

<img width="824" alt="Screen Shot 2019-06-18 at 4 06 05 PM" src="https://user-images.githubusercontent.com/1103622/59719903-1e17f100-91e3-11e9-9770-a095609d9265.png">

I'm happy to help with this, but wanted to file the issue first in case it's a known problem.

**Comment by heiglandreas** [comment]
Thanks for noticing! I'm not 100% sure, but the problem with papercall.io IIRC was that not all fields are actually required so it can happen that there actually is no event-date given. As that is a requirement for callingallpapers there might be a mismatch.

I'd be very grateful would you have a look at that!

**Comment by heiglandreas** [comment]
Though in this case the event date actually is given...

**Comment by karllhughes** [comment]
Looks like they changed the way event dates/locations are presented. I fixed it in the parser with this PR: https://github.com/joindin/callingallpapers-cli/pull/39
